name: Publish

on:
  push:
    tags: [ v* ]

env:
  DOTNET_VERSION: 7.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Use NuGet CLI
      uses: nuget/setup-nuget@v1

    - name: Setup Version
      id: setup_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    - name: Publish Application
      run: dotnet publish AppServiceProxy/AppServiceProxy.csproj -c Release -o ./publish -p:Version=${{ steps.setup_version.outputs.VERSION }}

    - name: Build NuGet package
      run: nuget pack AppServiceProxy.nuspec -BasePath ./publish -OutputDirectory ./dist -Version ${{ steps.setup_version.outputs.VERSION }}

    - name: Push NuGet Package
      run: dotnet nuget push dist/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
